//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieDataAccess
{
    using System;

    public partial class Movies
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Year { get; set; }
        public string Director { get; set; }
        public string Genre { get; set; }
        public string Synopsis { get; set; }
    }
}
